[package]
name = "konkuRRenz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
battle_plugin = { path = "battle_plugin"}

[workspace]
members = [
    "battle_plugin"
]
